# Database connection settings
hibernate.connection.url=jdbc:postgresql://localhost:8083/db-web-demo
hibernate.connection.username=psql-web-demo
hibernate.connection.password=web-demo#4passworD

# Echo all executed SQL to console
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true

# Automatically export the schema
hibernate.hbm2ddl.auto=create

